apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: z432le68w-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/z432le68w-dotnet-basic-gitops